title: Rajesh Kumar - Data Science Portfolio
description: Professional portfolio showcasing data analysis and IT experience
author:
  name: Rajesh Kumar
  email: kumarrajeshdangi@gmail.com
  location: Bhiwani, Haryana

social:
  linkedin: www.linkedin.com/in/rkd94
  github: RAJESH-KUMAR

skills:
  - SQL
  - Python
  - MS Power BI
  - MS Excel
  - CATIA
  - ANSYS

theme: jekyll-theme-minimal
