# Site Settings
title: Rajesh Kumar - Data Science Portfolio
description: Professional portfolio showcasing data analysis projects and skills

# Personal Information
author:
  name: Rajesh Kumar
  email: kumarrajeshdangi@gmail.com
  location: Bhiwani, Haryana

# Social Links
social:
  linkedin: www.linkedin.com/in/rkd94
  github: yourusername

# Professional Details
skills:
  - SQL
  - Python
  - MS Power BI
  - MS Excel
  - CATIA
  - ANSYS

# Theme Configuration
theme: jekyll-theme-minimal
